# Application Name
spring.application.name=crud-docker-application

# ===============================
# DATABASE CONFIGURATION
# ===============================

# Use service name "postgres" (from docker-compose)
spring.datasource.url=jdbc:postgresql://postgres:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=Abhii@2310
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================

# Automatically create/update tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console
spring.jpa.show-sql=true

# PostgreSQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Format SQL
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER CONFIGURATION
# ===============================

server.port=8080